version: "3.8"
services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - '3000:3000'
    stdin_open: true
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql
  mysql:
    build: ./mysql
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "qazWSXedc123"
      MYSQL_USER: "julian"
      MYSQL_PASSWORD: "qazWSXedc123"
    volumes:
      - ./schemas:/var/lib/mysql:rw